# Build and publish latest mdwritr image
name: Docker Image CI for GHCR
on:
  push:
    branches: main
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login ghcr.io --username jamesspearsv --password-stdin ${{ secrets.CR_PAT }}
          docker build . -t ghcr.io/jamesspearsv/mdwritr:latest
          docker push ghcr.io/jamesspearsv/mdwritr:latest
